### ISSUE TITLE
Feature-Request: Add `tagName()`

### ISSUE THREAD

**Issue by hepiyellow** [wix-incubator/unidriver#34]
Missing a `tagName()` that will get the element's `tagName` (e.g. span, div etc...)

**Comment by GabiGrin** [comment]
what is the use case?
By design, the library avoids doing things that involve implementation / isn't something a user can do.

Most tests around tag names can be tested otherwise, in ways that do not rely on checking the tag.
The only valid use case of checking the tag name IMO is when it's part of the feature itself - usually only when dealing with low level components. In those cases, it's valid to use the get native for the specific test or other solutions, as it is fair to say jsdom level tests will suffice here.
