### ISSUE TITLE
Feature-Request: Add `innerHtml` method

### ISSUE THREAD

**Issue by hepiyellow** [wix-incubator/unidriver#35]
If I have a component `<Text/>` which allows:
```js
<Text>
  hello
  <bold>world</bold>
 </Text>
```

And I am writing a TextDriver,
I was consumers of my driver to be able to get back what they passed as children.

I would add a `TextDriver.getInnerHtml()` for that.

`text()` is no good because it strips away the `<bold>` part.

**Comment by GabiGrin** [comment]
what is the use case?
By design, the library avoids doing things that involve implementation / isn't something a user can do.

Most tests around innerHtml can be tested otherwise.
If you want to make sure a certain component renders html, you can:
- use native element / other tools
- use unidriver to test for the existence of the tag inside: `assert(await $('.comp-with-html bold').text() === 'world')`
